baseurl = "https://www.lowrisc.org"
languageCode = "en-us"
title = "lowRISC"

[blackfriday]
plainIDAnchors = false

[permalinks]
blog="/blog/:year/:month/:slug"



[[menu.main]]
    name = "Jobs"
    identifier = "jobs"
    url = "/jobs/"
    weight = 1

[[menu.main]]
    name = "Our work"
    identifier = "our-work"
    url = "/our-work/"
    weight = 2

[[menu.main]]
    name = "Community"
    identifier = "community"
    url = "/community/"
    weight = 3

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 4

[[menu.main]]
    name = "About us"
    identifier = "about"
    url = "/about/"
    weight = 5

[[menu.main]]
    name = "Docs"
    identifier = "docs"
    url = "/docs/"
    weight = 6
